apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      name: debug-daemon
  template:
    metadata:
      labels:
        name: debug-daemon
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: debug-container
          image: ericdahl/eubuntu:latest
          command: [ "sleep", "infinity" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory